---
title: "wordcloud"
---

```{r, message=FALSE, warning=FALSE,echo=FALSE}
#| code-fold: true
#| code-summary: 'Importing Libraries'
#| warning: false
#| output: false
library(tidyverse)
library(ggplot2)
library(forecast)
library(astsa) 
library(xts)
library(tseries)
library(fpp2)
library(fma)
library(lubridate)
library(tidyverse)
library(TSstudio)
library(quantmod)
library(tidyquant)
library(plotly)
library(ggplot2)
library(imputeTS)
library(gridExtra)
library(reticulate)
library(readxl)
use_python("/usr/local/bin/python3", require = T)
knitr::knit_engines$set(python = reticulate::eng_python)
py_install("tensorflow")
```

```{r}
#| warning: false
#| code-fold: true


df5<-read.csv("Artists_TS_B.csv") #df\$album_release_year\<-as.Date("%y")

df5$artist_name<-as.factor(df5$artist_name)

df<-df5

#p<-ggplot(df5, aes(x = danceability, y = speechiness, color = artist_name)) + geom_point() + ggtitle("Wages and Services by industry in the US")

#ggplotly(p)
```

```{r}
#| warning: false
#| code-fold: true


library(dplyr)
library(wordcloud2)
library(tidyr)
library(tidytext)

# Assuming df is your dataframe

# Filter data for Taylor Swift and Beyoncé
taylor_swift_data <- df %>% 
  filter(artist_name == "Taylor Swift")

beyonce_data <- df %>% 
  filter(artist_name == "Beyoncé")

# Tokenize track names and count word frequencies for Taylor Swift
taylor_swift_word_freq <- taylor_swift_data %>%
  unnest_tokens(word, track_name) %>%
  count(word) %>%
  arrange(desc(n))

# Tokenize track names and count word frequencies for Beyoncé
beyonce_word_freq <- beyonce_data %>%
  unnest_tokens(word, track_name) %>%
  count(word) %>%
  arrange(desc(n))

```


```{r}
#| warning: false
#| code-fold: true

fig2<-wordcloud2(beyonce_word_freq, size = 1, backgroundColor = "white", color = ifelse(beyonce_word_freq[, 2] > 8, 'purple', 'green'))
fig2

```

## Word cloud Taylor Swift

```{r}
#| warning: false
#| code-fold: true
 
# Create word clouds for Taylor Swift and Beyoncé
fig1<-wordcloud2(taylor_swift_word_freq, size = 1, backgroundColor = "white", color = ifelse(taylor_swift_word_freq[, 2] > 8, 'red', 'skyblue'))
fig1
```